# Generated by Django 3.0.6 on 2020-05-29 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='fichas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ci', models.IntegerField()),
                ('nombre_apellidos', models.CharField(max_length=300)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('atendido', models.BooleanField(default=False)),
            ],
        ),
    ]
